# Henry's (2008) Word List
# Henry, Elaine. “Are Investors Influenced By How Earnings Press
# Releases Are Written.” The Journal of Business Communication 45, no. 4 (2008).


def lexicon2():

    henry_lex  = {}

    henry_lex ['ancaman'] 	 = -1.5
    henry_lex ['tidak pasti'] 	 = -1.5
    henry_lex ['melemah'] 	 = -1.5
    henry_lex ['rintangan'] 	 = -1.5
    henry_lex ['tertantang'] 	 = -1.5
    henry_lex ['menurun'] 	 = -1.5
    henry_lex ['menantang'] 	 = -1.5
    henry_lex ['hukuman'] 	 = -1.5
    henry_lex ['merosot'] 	 = -1.5
    henry_lex ['tantangan'] 	 = -1.5
    henry_lex ['berkurang'] 	 = -1.5
    henry_lex ['lebih buruk'] 	 = -1.5
    henry_lex ['mengecewakan'] 	 = -1.5
    henry_lex ['hambatan'] 	 = -1.5
    henry_lex ['memburuk'] 	 = -1.5
    henry_lex ['negatif'] 	 = -1.5
    henry_lex ['berisiko'] 	 = -1.5
    henry_lex ['menjatuhkan'] 	 = -1.5
    henry_lex ['jatuh'] 	 = -1.5
    henry_lex ['mempertaruhkan'] 	 = -1.5
    henry_lex ['menurun'] 	 = -1.5
    henry_lex ['mengecewakan'] 	 = -1.5
    henry_lex ['gagal'] 	 = -1.5
    henry_lex ['gagal'] 	 = -1.5
    henry_lex ['penalti'] 	 = -1.5
    henry_lex ['kelemahan'] 	 = -1.5
    henry_lex ['paling sedikit'] 	 = -1.5
    henry_lex ['menurun'] 	 = -1.5
    henry_lex ['merosot'] 	 = -1.5
    henry_lex ['memburuk'] 	 = -1.5
    henry_lex ['tetes'] 	 = -1.5
    henry_lex ['lebih sedikit'] 	 = -1.5
    henry_lex ['melemahkan'] 	 = -1.5
    henry_lex ['lemah'] 	 = -1.5
    henry_lex ['kesulitan'] 	 = -1.5
    henry_lex ['menolak'] 	 = -1.5
    henry_lex ['menyusut'] 	 = -1.5
    henry_lex ['di bawah'] 	 = -1.5
    henry_lex ['lebih rendah'] 	 = -1.5
    henry_lex ['ketakpastian'] 	 = -1.5
    henry_lex ['menjatuhkan'] 	 = -1.5
    henry_lex ['mengecewakan'] 	 = -1.5
    henry_lex ['ancaman'] 	 = -1.5
    henry_lex ['rintangan'] 	 = -1.5
    henry_lex ['di bawah'] 	 = -1.5
    henry_lex ['kekecewaan'] 	 = -1.5
    henry_lex ['murung'] 	 = -1.5
    henry_lex ['jatuhan'] 	 = -1.5
    henry_lex ['menyusut'] 	 = -1.5
    henry_lex ['memburuk'] 	 = -1.5
    henry_lex ['kegagalan'] 	 = -1.5
    henry_lex ['kecewa'] 	 = -1.5
    henry_lex ['terendah'] 	 = -1.5
    henry_lex ['lari gawang'] 	 = -1.5
    henry_lex ['tantangan'] 	 = -1.5
    henry_lex ['turun'] 	 = -1.5
    henry_lex ['merosot'] 	 = -1.5
    henry_lex ['penyusutan'] 	 = -1.5
    henry_lex ['risiko'] 	 = -1.5
    henry_lex ['gelisah'] 	 = -1.5
    henry_lex ['terkecil'] 	 = -1.5
    henry_lex ['kecenderungan untuk menurun'] 	 = -1.5
    henry_lex ['melemah'] 	 = -1.5
    henry_lex ['jatuh'] 	 = -1.5
    henry_lex ['kelemahan'] 	 = -1.5
    henry_lex ['kemerosotan'] 	 = -1.5
    henry_lex ['kegagalan'] 	 = -1.5
    henry_lex ['menolak'] 	 = -1.5
    henry_lex ['menyusut'] 	 = -1.5
    henry_lex ['memburuk'] 	 = -1.5
    henry_lex ['memburuk'] 	 = -1.5
    henry_lex ['sulit'] 	 = -1.5
    henry_lex ['rendah'] 	 = -1.5
    henry_lex ['memburuk'] 	 = -1.5
    henry_lex ['mengurangi'] 	 = -1.5
    henry_lex ['tidak menguntungkan'] 	 = -1.5
    henry_lex ['memburuk'] 	 = -1.5
    henry_lex ['menjatuhkan'] 	 = -1.5
    henry_lex ['air terjun'] 	 = -1.5
    henry_lex ['terburuk'] 	 = -1.5
    henry_lex ['ditolak'] 	 = -1.5
    henry_lex ['jatuh'] 	 = -1.5
    henry_lex ['negatif'] 	 = -1.5
    henry_lex ['lebih kecil'] 	 = -1.5
    henry_lex ['pelemahan'] 	 = -1.5
    henry_lex ['memperbaiki'] 	 = 1.5
    henry_lex ['pemimpin'] 	 = 1.5
    henry_lex ['membaik'] 	 = 1.5
    henry_lex ['terkuat'] 	 = 1.5
    henry_lex ['lebih tinggi'] 	 = 1.5
    henry_lex ['berhasil'] 	 = 1.5
    henry_lex ['menikmati'] 	 = 1.5
    henry_lex ['ke atas'] 	 = 1.5
    henry_lex ['terbaik'] 	 = 1.5
    henry_lex ['pertumbuhan'] 	 = 1.5
    henry_lex ['hadiah'] 	 = 1.5
    henry_lex ['peluang'] 	 = 1.5
    henry_lex ['Bagus'] 	 = 1.0
    henry_lex ['didorong'] 	 = 1.5
    henry_lex ['memperluas'] 	 = 1.5
    henry_lex ['melebihi'] 	 = 1.5
    henry_lex ['ekspansi'] 	 = 1.5
    henry_lex ['peningkatan'] 	 = 1.5
    henry_lex ['ditingkatkan'] 	 = 1.5
    henry_lex ['lebih baik'] 	 = 1.5
    henry_lex ['lebih besar'] 	 = 1.5
    henry_lex ['berhasil'] 	 = 1.5
    henry_lex ['meraih'] 	 = 1.5
    henry_lex ['memperkuat'] 	 = 1.5
    henry_lex ['berhasil'] 	 = 1.5
    henry_lex ['bermanfaat'] 	 = 1.5
    henry_lex ['imbalan'] 	 = 1.5
    henry_lex ['mengembang'] 	 = 1.5
    henry_lex ['kepastian'] 	 = 1.5
    henry_lex ['mencapai'] 	 = 1.5
    henry_lex ['tumbuh'] 	 = 1.5
    henry_lex ['catatan'] 	 = 1.5
    henry_lex ['berhasil'] 	 = 1.5
    henry_lex ['dewasa'] 	 = 1.5
    henry_lex ['mengalami kemajuan'] 	 = 1.5
    henry_lex ['terbesar'] 	 = 1.5
    henry_lex ['di atas'] 	 = 1.5
    henry_lex ['penguatan'] 	 = 1.5
    henry_lex ['membaik'] 	 = 1.5
    henry_lex ['kuat'] 	 = 1.5
    henry_lex ['lebih kuat'] 	 = 1.5
    henry_lex ['kekuatan'] 	 = 1.5
    henry_lex ['tinggi'] 	 = 1.5
    henry_lex ['perbaikan'] 	 = 1.5
    henry_lex ['padat'] 	 = 1.5
    henry_lex ['menyelesaikan'] 	 = 1.5
    henry_lex ['bangkit'] 	 = 1.5
    henry_lex ['paling tinggi'] 	 = 1.5
    henry_lex ['memperkuat'] 	 = 1.5
    henry_lex ['mawar'] 	 = 1.5
    henry_lex ['positif'] 	 = 1.5
    henry_lex ['mengantarkan'] 	 = 1.5
    henry_lex ['terlampaui'] 	 = 1.5
    henry_lex ['lebih besar'] 	 = 1.5
    henry_lex ['mencapai'] 	 = 1.5
    henry_lex ['bagus sekali'] 	 = 1.5
    henry_lex ['bangkit'] 	 = 1.5
    henry_lex ['melampaui'] 	 = 1.5
    henry_lex ['tumbuh'] 	 = 1.5
    henry_lex ['memperluas'] 	 = 1.5
    henry_lex ['memberikan'] 	 = 1.5
    henry_lex ['ahli'] 	 = 1.5
    henry_lex ['menikmati'] 	 = 1.5
    henry_lex ['peluang'] 	 = 1.5
    henry_lex ['paling'] 	 = 1.5
    henry_lex ['pasti'] 	 = 1.5
    henry_lex ['berhasil'] 	 = 1.5
    henry_lex ['prestasi'] 	 = 1.5
    henry_lex ['kenaikan'] 	 = 1.5
    henry_lex ['prestasi'] 	 = 1.5
    henry_lex ['lagi'] 	 = 1.5
    henry_lex ['tercapai'] 	 = 1.5
    henry_lex ['keberhasilan'] 	 = 1.5
    henry_lex ['menikmati'] 	 = 1.5
    henry_lex ['meningkat'] 	 = 1.5
    henry_lex ['kesuksesan'] 	 = 1.5
    henry_lex ['melebihi'] 	 = 1.5
    henry_lex ['yakin'] 	 = 1.5
    henry_lex ['prestasi'] 	 = 1.5
    henry_lex ['mengalahkan'] 	 = 1.5
    henry_lex ['positif'] 	 = 1.5
    henry_lex ['mencapai'] 	 = 1.5
    henry_lex ['ketukan'] 	 = 1.5
    henry_lex ['kemajuan'] 	 = 1.5
    henry_lex ['terkemuka'] 	 = 1.5
    henry_lex ['tumbuh'] 	 = 1.5
    henry_lex ['pencapaian'] 	 = 1.5
    henry_lex ['diperluas'] 	 = 1.5
    henry_lex ['pertumbuhan'] 	 = 1.5
    henry_lex ['dinikmati'] 	 = 1.5
    henry_lex ['diperkuat'] 	 = 1.5
    henry_lex ['terkirim'] 	 = 1.5
    henry_lex ['senang'] 	 = 1.5
    henry_lex ['menyampaikan'] 	 = 1.5
    henry_lex ['ditingkatkan'] 	 = 1.5
    henry_lex ['sukses'] 	 = 1.5
    henry_lex ['terbesar'] 	 = 1.5
    henry_lex ['meningkat'] 	 = 1.5
    henry_lex ['memberi semangat'] 	 = 1.5
    henry_lex ['meningkatkan'] 	 = 1.5
    henry_lex ['naik'] 	 = 1.5
    henry_lex ['kekuatan'] 	 = 1.5
    henry_lex ['dihargai'] 	 = 1.5
    henry_lex ['mengalahkan'] 	 = 1.5

    return henry_lex 